//GLSL version to use
#version 460

#include "utils.glsl"

//size of a workgroup for compute
layout (local_size_x = 16, local_size_y = 16) in;

//descriptor bindings for the pipeline
layout(rgba16f,set = 0, binding = 0) uniform image2D image;
layout(push_constant) readonly uniform CSPerFrame
{
    vec3 camPos; float _rs2;
    mat4 invView;
    float fovy;
    float aspect;
} csPerFrame;

#define MAX_GRID_SIZE 100

layout(align = 16, set = 0, binding = 1) readonly buffer CSPerScene
{
    mat4 worldTransform;
    ivec2 voxels[MAX_GRID_SIZE * MAX_GRID_SIZE * MAX_GRID_SIZE];
} csPerScene;


struct RayTraverseResult
{
    bool hit;
    ivec2 voxel;
};

RayTraverseResult TraverseVoxelGridOptimized(vec3 rayOrigin, vec3 rayDirection, float maxDist) {
    RayTraverseResult result = {false, ivec2(0, 0)};

    ivec3 coord = ivec3(floor(rayOrigin));
    ivec3 prevCoord = coord - 1;
    
    vec3 rayStep = sign(rayDirection);
    vec3 tDelta = abs(1.0 / rayDirection);
    
    vec3 tMax = (sign(rayDirection) * (vec3(coord) - rayOrigin) + (sign(rayDirection) * 0.5) + 0.5) * tDelta;
    
    while (length(rayOrigin - vec3(coord)) < maxDist) { 
        if (all(greaterThanEqual(coord, ivec3(0))) && all(lessThan(coord, ivec3(MAX_GRID_SIZE, MAX_GRID_SIZE, MAX_GRID_SIZE))))
        {
            ivec2 voxel = csPerScene.voxels[coord.x * MAX_GRID_SIZE * MAX_GRID_SIZE + coord.y * MAX_GRID_SIZE + coord.z];
            if (voxel.x > 0)
            {
                result.hit = true;
                result.voxel = voxel;
                return result;
            }
        }

        bvec3 comp = lessThan(tMax.xyz, min(tMax.yzx, tMax.zxy));
        tMax += vec3(comp) * tDelta;
        ivec3 nextCoord = coord + ivec3(comp) * ivec3(rayStep);
        if(coord == nextCoord) return result;
        coord = nextCoord;
    }
    return result;
}

void main() 
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    ivec2 extents = size / 2;

    float fovy = csPerFrame.fovy;

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        float pX = (2*(float(texelCoord.x) / size.x) - 1) * csPerFrame.aspect * tan(fovy / 2);
        float pY = (1 - 2*(float(texelCoord.y) / size.y)) * tan(fovy / 2);

        vec3 rayOrigin = vec3(vec4(0, 0, 0, 1) * csPerFrame.invView);
        vec3 rayTarget = vec3(vec4(pX, pY, 1, 1) * csPerFrame.invView);
        vec3 rayDirection = normalize(rayTarget - rayOrigin);
        vec3 camPos = csPerFrame.camPos;

        RayTraverseResult rayTraverse =  TraverseVoxelGridOptimized(rayOrigin, rayDirection, 100.0);
        if(rayTraverse.hit) imageStore(image, texelCoord, U32ToVec4(rayTraverse.voxel.y));
    }
}